### ISSUE TITLE
Token Ids are negative when preprocessed.

### ISSUE THREAD

**Issue by thak123** [shoarora/lmtuners#12]
Hi,

I am trying to run the code in the repo with **bert-base-multilingual-cased-vocab.txt** vocab
But tokens being converted to  ids when preprocessed are negative. 
when passed to the network throws this error.

I tried ranging  the max-length from 64 to 256.

RuntimeError: index out of range: Tried to access index -28619 out of table with 119546 rows. at /tmp/pip-req-build-ufslq_a9/aten/src/TH/generic/THTensorEvenMoreMath.cpp:418

**Comment by shoarora** [comment]
I believe issue is the tokenization script is saving the token ids with dtype `torch.int16` so you're hitting an overflow error.  

I intend to make some fixes this week to the tokenization/padding to be more memory efficient.  In the meantime, you can adjust the tokenization script to your needs.

**Comment by thak123** [comment]
Thanks @shoarora  for the reply.

**Comment by thak123** [comment]
@shoarora  I changes the dtype torch.int16 to torch.long now this error is gone and facing new error

> $ /home/gaurish/miniconda3/bin/python /media/gaurish/angela/projects/lv-twitter-sa/lmtuners/experiments/disc_lm_small/train_electra_small.py
set hparams: DiscLMTrainingModuleConfig(d_loss_weight=50, epsilon=1e-06, learning_rate=0.0005, lr_schedule='linear', num_steps=1000000.0, save_on_val=False, save_path='electra-small', warmup_steps=10000, weight_decay=0.01)
Validation sanity check:   0%|                                                                                        | 0/5 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/media/gaurish/angela/projects/lv-twitter-sa/lmtuners/experiments/disc_lm_small/train_electra_small.py", line 141, in <module>
    fire.Fire(main)
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/fire-0.3.0-py3.7.egg/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/fire-0.3.0-py3.7.egg/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/fire-0.3.0-py3.7.egg/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/media/gaurish/angela/projects/lv-twitter-sa/lmtuners/experiments/disc_lm_small/train_electra_small.py", line 96, in main
    trainer.fit(lightning_module, train_loader, val_loader)
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/pytorch_lightning-0.7.1-py3.7.egg/pytorch_lightning/trainer/trainer.py", line 630, in fit
    self.run_pretrain_routine(model)
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/pytorch_lightning-0.7.1-py3.7.egg/pytorch_lightning/trainer/trainer.py", line 809, in run_pretrain_routine
    False)
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/pytorch_lightning-0.7.1-py3.7.egg/pytorch_lightning/trainer/evaluation_loop.py", line 262, in evaluate
    output = self.evaluation_forward(model, batch, batch_idx, dataloader_idx, test_mode)
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/pytorch_lightning-0.7.1-py3.7.egg/pytorch_lightning/trainer/evaluation_loop.py", line 439, in evaluation_forward
    output = model.validation_step(*args)
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/lmtuners-0.1.0-py3.7.egg/lmtuners/lightning_modules/discriminative_lm.py", line 128, in validation_step
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/lmtuners-0.1.0-py3.7.egg/lmtuners/lightning_modules/discriminative_lm.py", line 65, in forward
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/transformers/modeling_bert.py", line 987, in forward
    encoder_attention_mask=encoder_attention_mask,
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/transformers/modeling_bert.py", line 783, in forward
    input_ids=input_ids, position_ids=position_ids, token_type_ids=token_type_ids, inputs_embeds=inputs_embeds
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/transformers/modeling_bert.py", line 174, in forward
    position_embeddings = self.position_embeddings(position_ids)
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1484, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: index out of range: Tried to access index 128 out of table with 127 rows. at /tmp/pip-req-build-ufslq_a9/aten/src/TH/generic/THTensorEvenMoreMath.cpp:418

**Comment by shoarora** [comment]
>   File "/home/gaurish/miniconda3/lib/python3.7/site-packages/transformers/modeling_bert.py", line 174, in forward
> 
>     position_embeddings = self.position_embeddings(position_ids)
> 
>   File "/home/gaurish/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
> 
>     result = self.forward(*input, **kwargs)
> 
>   File "/home/gaurish/miniconda3/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 114, in forward
> 
>     self.norm_type, self.scale_grad_by_freq, self.sparse)
> 
>   File "/home/gaurish/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1484, in embedding
> 
>     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
> 
> RuntimeError: index out of range: Tried to access index 128 out of table with 127 rows. at /tmp/pip-req-build-ufslq_a9/aten/src/TH/generic/THTensorEvenMoreMath.cpp:418


looks like a max_length issue to me. double check the length of your data points vs max_length set on your model. particularly, there could be a mismatch if you’re combining two segments into one data point in the data preprocessing step

**Comment by thak123** [comment]
Gonna do that now.

**Comment by shoarora** [comment]
#13 should handle the needs
